### ISSUE TITLE
Lijsten ophalen werkt niet meer na vernieuwing Wrts

### ISSUE THREAD

**Issue by newnick** [tkon99/OverhoorMij#1]
Wrts heeft de website vernieuwd en de api verwijdert waardoor het ophalen van de lijsten niet meer werkt.
![oudewrtswasbeter](https://cloud.githubusercontent.com/assets/3309700/9688601/713781e8-5330-11e5-8031-2882f4f0dec9.PNG)

**Comment by tkon99** [comment]
Klopt inderdaad, dit project is een soort van "vergeten". Het werkt ook niet echt en dat heeft het nooit gedaan. Komt door de mix van php en js die ik nu niet meer zou toepassen voor dit soort doeleinden. Het idee komt echter terug in simplyHomework wanneer we daar overhoor mogelijkheden aan toevoegen. (Begin 2016)

Je kunt hem natuurlijk altijd clonen en updaten voor de nieuwe versie. Ik zal je pull-requests met plezier accepteren.
